### ISSUE TITLE
lua.dll not found

### ISSUE THREAD

**Issue by jrichardsz** [SayCV/tools-Shuame#1]
Hello.
First, thanks for this tool. 
It helped to restore the file: system/etc/vold.fstab.nand
When I damaged it , trying to swap the internal memory for external sdcard on my android.

For securiry, i run this tool on my virtual machine and works!!.
Now when i run in my windows 7, i get this error:

![shuame-error](https://f.cloud.github.com/assets/3322836/2116615/e864191a-9091-11e3-8ec4-0c4d5f982eec.png)

I solved, copying lua.dll from a clean install of shuame from official web.

Do you rin this on windows 7? It is a problem of my machine?

What is the reason for the need lua.dll?

Thanks in advance!!

**Comment by SayCV** [comment]
I had add lua.dll
